# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Electricity Demand Forecasting Challenge
short_description: This use case consists of a machine learning problem applied to the field of utilities. The goal is to forecast the electricity demand for 7 days, for 30 condos in Ecuador.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.png
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Leaderboard of the challenge
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2021-06-13 12:00:00
end_date: 2021-07-15 12:00:00
published: True
allowed_email_domain: ["sdggroup.com", "polimi.it", "mail.polimi.it", "univr.it", "studenti.univr.it", "unimib.it", "campus.unimib.it", "unipd.it", "studenti.unipd.it", "studenti.unibg.it" ]

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["RMSE", "Score"],
        "default_order_by": "Score",
      }

challenge_phases:
  - id: 1
    name: Phase1
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2021-06-13 12:00:00
    end_date: 2021-07-15 12:00:00
    test_annotation_file: annotations/test_annotation_file.csv
    codename: test
    max_submissions_per_day: 10
    max_submissions_per_month: 30
    max_submissions: 30
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Data
    codename: all_data

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
